using MySql.Data.MySqlClient;
using System;
using System.Configuration;
using System.IO;
using System.Windows;

namespace UIKitTutorials
{
    /// <summary>
    /// Lógica de interacción para MainWindow.xaml
    /// </summary>
    public partial class MainWindow : Window
    {
        
        public MainWindow()
        {
            Logger("Beggining of Main", "Application Started");

            //open login page as a popup

            var wd = new Pages.Login();
            wd.Title = "Please Login";
            wd.ShowDialog();


            InitializeComponent();
            //Load this as the first page on startup
            PagesNavigation.Navigate(new System.Uri("Pages/StartPage.xaml", UriKind.RelativeOrAbsolute));
        }

        private void btnClose_Click(object sender, RoutedEventArgs e)
        {
            Close();
        }

        private void btnRestore_Click(object sender, RoutedEventArgs e)
        {
            if (WindowState == WindowState.Normal)
                WindowState = WindowState.Maximized;
            else
                WindowState = WindowState.Normal;
        }

        private void btnMinimize_Click(object sender, RoutedEventArgs e)
        {
            WindowState = WindowState.Minimized;
        }

        private void rdHome_Click(object sender, RoutedEventArgs e)
        {
            // PagesNavigation.Navigate(new HomePage());

            PagesNavigation.Navigate(new System.Uri("Pages/HomePage.xaml", UriKind.RelativeOrAbsolute));
        }

        private void rdSounds_Click(object sender, RoutedEventArgs e)
        {
            PagesNavigation.Navigate(new System.Uri("Pages/SoundsPage.xaml", UriKind.RelativeOrAbsolute));
        }

        private void rdNotes_Click(object sender, RoutedEventArgs e)
        {
            PagesNavigation.Navigate(new System.Uri("Pages/NotesPage.xaml", UriKind.RelativeOrAbsolute));
        }

        private void rdPayment_Click(object sender, RoutedEventArgs e)
        {
            PagesNavigation.Navigate(new System.Uri("Pages/PaymentPage.xaml", UriKind.RelativeOrAbsolute));
        }

        private void Ellipse_MouseDown(object sender, System.Windows.Input.MouseButtonEventArgs e)
        {
            Logger("View", "Opened Settings");
            PagesNavigation.Navigate(new System.Uri("Pages/Settings.xaml", UriKind.RelativeOrAbsolute));
        }

        public void Logger(string action, string message)
        {
            var dir = Directory.GetCurrentDirectory() + "\\Logs";
            if (Directory.Exists(dir))
            {
                DateTime now = DateTime.Now;
                DateTime today = DateTime.Today;
                string filename = dir + "\\" + today.ToString("yyyy-MM-dd") + ".txt";
                using (StreamWriter sr = File.AppendText(filename))
                {
                    sr.WriteLine($"[Time:] [{now.ToString("yyyy-MM-dd HH:mm:ss")}] [Event:] {action} [lOG:]-->" + message);
                    sr.Close();
                }
            }
            else
            {
                DateTime today = DateTime.Today;
                Directory.CreateDirectory(dir);
                string filename = dir + "\\" + today.ToString("yyyy-MM-dd") + ".txt";
                StreamWriter sw = File.AppendText(filename);
                sw.WriteLine($"This log file was generated by Student Management System on {today.ToString("yyyy - MM - dd HH: mm:ss")}");
                sw.Close();
                Logger("FileSystem", "Created logs folder");
            }

        }

        private void home_Closing(object sender, System.ComponentModel.CancelEventArgs e)
        {
            
            Logger("End", "Exiting");
        }
        
        public void confupdater(string name,string value)
        {
            Configuration config = ConfigurationManager.OpenExeConfiguration(ConfigurationUserLevel.None);
            config.AppSettings.Settings[name].Value = value;
            config.Save(ConfigurationSaveMode.Modified);
            Logger("Configuration",$"Updated {name}");
        }
    }
}
