using System;
using System.Configuration;
using System.IO;
using System.Windows;
using MySql.Data.MySqlClient;

namespace UIKitTutorials.Pages
{
    /// <summary>
    /// Interaction logic for Login.xaml
    /// </summary>
    public partial class Login : Window
    {


        public Login()
        {
            string state = FetchConf("state");
            string remMe = FetchConf("remMe");
            string us = FetchConf("user");
            string pass = FetchConf("password");
            InitializeComponent();


            //if it is first install
            if (state == "1" ){sqlsettings.IsExpanded = true;}else { fill(); }

        }
        private void fill()
        {
            string remMe = FetchConf("remMe");
            string us = FetchConf("user");
            string pass = FetchConf("password");
            string serv = FetchConf("server");
            if (remMe == "true")
            {
                //display data
                Userpassword.Text = pass;
                Username.Text = us;
                sqlserver.Text = serv;
                checkbox.IsChecked = true;
            }else if (remMe == "false")
            {
                checkbox.IsChecked = false;
                sqlsettings.IsExpanded = true;
            }

        }

        private void Window_Closing(object sender, System.ComponentModel.CancelEventArgs e)
        {
            //Application.Current.Shutdown();
        }

        private void Button_Click(object sender, RoutedEventArgs e)
        {
            Application.Current.Shutdown();

        }

        private void Login1_Click(object sender, RoutedEventArgs e)
        {


            string connString;
            MySqlConnection conn;
            string user = Username.Text;
            var password = Userpassword.Text;
            var server = sqlserver.Text;
            //save the current data in textbox
            if (checkbox.IsChecked == true)
            {
                confupdater("user", $"{user}");
                confupdater("password", $"{password}");
                confupdater("server", $"{server}");
                confupdater("remMe", "true");
            }
            else if (checkbox.IsChecked == false)
            {
                confupdater("user", "");
                confupdater("password", "");
                confupdater("server", "");
                confupdater("remMe", "false");
            }

            confupdater("state", "0");
            string database = FetchConf("database");
            connString = $"SERVER={server};DATABASE={database};USER={user};PASSWORD={password}";
            conn = new MySqlConnection(connString);
            try
            {
                Logger("Database", "Start connection");
                conn.Open();
                Logger("Database", "Connected successfully");
                Close();

            }
            catch (Exception ex)
            {

                string msg = ex.ToString();
                var wd = new Dialogue(msg);
                Logger("Database", $"Error connecting; {ex}");
                wd.ShowDialog();
                Logger("Database", "Failed to connect with MySQL check to see if mysql is running");


            }
        }

        public string FetchConf(string name)
        {
            var result = ConfigurationManager.AppSettings.Get(name);
            return result;
        }

        public void Logger(string action, string message)
        {
            var dir = Directory.GetCurrentDirectory() + "\\Logs";
            if (Directory.Exists(dir))
            {
                DateTime now = DateTime.Now;
                DateTime today = DateTime.Today;
                string filename = dir + "\\" + today.ToString("yyyy-MM-dd") + ".txt";
                using (StreamWriter sr = File.AppendText(filename))
                {
                    sr.WriteLine($"[Time:] [{now.ToString("yyyy-MM-dd HH:mm:ss")}] [Event:] {action} [lOG:]-->" + message);
                    sr.Close();
                }
            }
            else
            {
                DateTime today = DateTime.Today;
                Directory.CreateDirectory(dir);
                string filename = dir + "\\" + today.ToString("yyyy-MM-dd") + ".txt";
                StreamWriter sw = File.AppendText(filename);
                sw.WriteLine($"This log file was generated by Student Management System on {today.ToString("yyyy - MM - dd HH: mm:ss")}");
                sw.Close();
                Logger("FileSystem", "Created logs folder");
            }

        }

        public void confupdater(string name, string value)
        {
            Configuration config = ConfigurationManager.OpenExeConfiguration(ConfigurationUserLevel.None);
            config.AppSettings.Settings[name].Value = value;
            config.Save(ConfigurationSaveMode.Modified);
            Logger("Configuration", $"Updated {name}");
        }

    }
}